name: docker build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker build
        run: |
            SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c 1-7)
            docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
            docker build -t pocketfoundation/release-watch:${SHORT_SHA} .
            docker push pocketfoundation/release-watch:${SHORT_SHA}
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}